# Generated by scripts/sync_canonical_package.py; do not edit directly.
"""Console output helpers that preserve diagnostics on legacy encodings."""

from __future__ import annotations

import sys
from typing import TextIO


def safe_print(message: object, *, file: TextIO | None = None) -> None:
    """Print text while escaping characters unsupported by the output stream."""
    target = file if file is not None else sys.stdout
    text = str(message)
    try:
        print(text, file=target)
    except UnicodeEncodeError:
        encoding = target.encoding or "utf-8"
        safe_text = text.encode(encoding, errors="backslashreplace").decode(
            encoding, errors="replace"
        )
        print(safe_text, file=target)
