# Generated by scripts/sync_canonical_package.py; do not edit directly.
"""Generated by the release workflow; do not edit in a built package."""

BRIDGE_RELEASE_VERSION: str | None = '2.3.2'
BRIDGE_SHA256: dict[str, str] = {
    'fbchat-bridge-e2ee-darwin-amd64': '57438de5b4ad91d5940c06a6375816849add946eb1f1eaec902e7c049f401343',
    'fbchat-bridge-e2ee-darwin-arm64': 'f20492cb258012c17c3626b9dced469b04d3dd205fcb30afc3cb7df2d454c8f7',
    'fbchat-bridge-e2ee-linux-amd64': '6a724d0d5799405dead1354b28fed69a989efc2785a0ebcf7bf66cfb1a4c6985',
    'fbchat-bridge-e2ee-linux-arm64': '82d98374cccfee83e2d5b7e40782dcdc3dfa3821282cb178c69d87c1d123026e',
    'fbchat-bridge-e2ee-windows-amd64.exe': '2216fc299df618b6c1aeee1c00bcf9e1ab55aed1073588bff6fb7ecd142f95fe',
}
