"""Build the canonical ``fbchat_v2`` package from the legacy source layout.

The repository keeps the historical ``src/_core``, ``src/_features`` and
``src/_messaging`` trees as the editable implementation.  Published wheels,
however, must expose only the collision-safe ``fbchat_v2`` namespace.  This
script creates a deterministic source snapshot for that namespace and rewrites
internal absolute imports so an installed wheel never depends on generic
top-level packages such as ``_core``.
"""

from __future__ import annotations

import argparse
import ast
import os
import re
import stat
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = PROJECT_ROOT / "src"
TARGET_ROOT = SOURCE_ROOT / "fbchat_v2"
SOURCE_PACKAGES = ("_core", "_features", "_messaging")
MANUAL_TARGET_FILES = frozenset(
    {
        TARGET_ROOT / "__init__.py",
        TARGET_ROOT / "py.typed",
    }
)
GENERATED_HEADER = (
    "# Generated by scripts/sync_canonical_package.py; do not edit directly.\n"
)
GENERATED_MARKDOWN_HEADER = (
    "<!-- Generated by scripts/sync_canonical_package.py; do not edit directly. -->\n"
)
SOURCE_PATTERNS = ("*.py", "README.md", "README_EN.md")
FEATURES_INIT = '''"""Feature packages published under the canonical namespace."""

__all__ = ["_facebook", "_thread"]
'''

_SOURCE_PACKAGE_PATTERN = "|".join(re.escape(name) for name in SOURCE_PACKAGES)
_FROM_IMPORT = re.compile(
    rf"(?m)^(?P<prefix>[ \t]*from[ \t]+)"
    rf"(?P<package>{_SOURCE_PACKAGE_PATTERN})(?=\.|[ \t]+import\b)"
)
_PLAIN_IMPORT = re.compile(
    rf"(?P<prefix>(?:^|,)[ \t]*)(?P<package>{_SOURCE_PACKAGE_PATTERN})"
    rf"(?=\.|[ \t]+as\b|[ \t]*(?:,|#|$))"
)
_LAYOUT_REWRITES: dict[Path, tuple[tuple[str, str], ...]] = {
    Path("_core/_facebookLogin.py"): (
        (
            'os.path.join(os.path.dirname(__file__), "..", "..", ".env")',
            'os.path.join(os.path.dirname(__file__), "..", "..", "..", ".env")',
        ),
    ),
    Path("_messaging/_listening_e2ee.py"): (
        ("project_root = here.parents[2]", "project_root = here.parents[3]"),
        (
            "Path(__file__).resolve().parents[2]",
            "Path(__file__).resolve().parents[3]",
        ),
    ),
}


def _rewrite_plain_import_line(line: str) -> str:
    if re.match(r"^[ \t]*import[ \t]+", line) is None:
        return line
    keyword_end = re.match(r"^[ \t]*import[ \t]+", line)
    if keyword_end is None:  # pragma: no cover - guarded above
        return line
    prefix = line[: keyword_end.end()]
    imports = line[keyword_end.end() :]
    return prefix + _PLAIN_IMPORT.sub(
        lambda match: f"{match.group('prefix')}fbchat_v2.{match.group('package')}",
        imports,
    )


def _legacy_imports(source: str, origin: Path) -> list[str]:
    """Return runtime imports that still target a generic top-level package."""
    try:
        tree = ast.parse(source, filename=str(origin))
    except SyntaxError as exc:
        raise RuntimeError(f"Cannot parse Python source: {origin}") from exc

    invalid: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            root = node.module.partition(".")[0]
            if root in SOURCE_PACKAGES:
                invalid.append(f"line {node.lineno}: from {node.module}")
        elif isinstance(node, ast.Import):
            for alias in node.names:
                root = alias.name.partition(".")[0]
                if root in SOURCE_PACKAGES:
                    invalid.append(f"line {node.lineno}: import {alias.name}")
    return invalid


def rewrite_imports(source: str, origin: Path) -> str:
    """Rewrite internal imports and reject syntax the synchronizer missed."""
    rewritten = rewrite_text_imports(source)
    invalid = _legacy_imports(rewritten, origin)
    if invalid:
        details = ", ".join(invalid)
        raise RuntimeError(f"Internal import was not rewritten in {origin}: {details}")
    return rewritten


def rewrite_text_imports(source: str) -> str:
    """Rewrite import examples without broadly replacing prose identifiers."""
    rewritten = _FROM_IMPORT.sub(
        lambda match: f"{match.group('prefix')}fbchat_v2.{match.group('package')}",
        source,
    )
    rewritten = "".join(
        _rewrite_plain_import_line(line) for line in rewritten.splitlines(keepends=True)
    )
    return rewritten


def rewrite_documentation(source: str) -> str:
    """Rewrite canonical source paths and import examples in copied Markdown."""
    rewritten = rewrite_text_imports(source)
    for package_name in SOURCE_PACKAGES:
        rewritten = rewritten.replace(
            f"src/{package_name}", f"src/fbchat_v2/{package_name}"
        )
    return rewritten


def rewrite_layout_paths(source: str, relative_path: Path, origin: Path) -> str:
    """Adjust the fixed extra namespace level in known layout-sensitive modules."""
    for old, new in _LAYOUT_REWRITES.get(relative_path, ()):
        if old not in source:
            raise RuntimeError(
                f"Expected layout expression is missing in {origin}: {old}"
            )
        source = source.replace(old, new)
    return source


def expected_snapshot() -> dict[Path, str]:
    """Return every generated path and its normalized UTF-8 content."""
    expected: dict[Path, str] = {}
    for package_name in SOURCE_PACKAGES:
        package_root = SOURCE_ROOT / package_name
        if not package_root.is_dir():
            raise FileNotFoundError(f"Source package does not exist: {package_root}")
        source_paths = {
            path
            for pattern in SOURCE_PATTERNS
            for path in package_root.rglob(pattern)
            if path.is_file()
        }
        for source_path in sorted(source_paths):
            relative = source_path.relative_to(SOURCE_ROOT)
            target_path = TARGET_ROOT / relative
            source = source_path.read_text(encoding="utf-8", errors="strict")
            if source_path.suffix == ".py":
                rewritten = rewrite_imports(source, source_path)
                rewritten = rewrite_layout_paths(rewritten, relative, source_path)
                expected[target_path] = GENERATED_HEADER + rewritten
            else:
                expected[target_path] = (
                    GENERATED_MARKDOWN_HEADER + rewrite_documentation(source)
                )

    features_init = TARGET_ROOT / "_features" / "__init__.py"
    expected[features_init] = GENERATED_HEADER + FEATURES_INIT
    return expected


def canonical_package_members(
    expected: dict[Path, str] | None = None,
) -> frozenset[str]:
    """Return the exact files allowed below the published package root."""
    if expected is None:
        expected = expected_snapshot()
    paths = set(expected) | set(MANUAL_TARGET_FILES)
    return frozenset(path.relative_to(SOURCE_ROOT).as_posix() for path in paths)


def is_link_like_stat(mode: int, file_attributes: int = 0) -> bool:
    """Recognize POSIX links and Windows reparse points without following them."""
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return stat.S_ISLNK(mode) or bool(file_attributes & reparse_flag)


def _entry_kind(path: Path) -> str:
    try:
        entry_stat = path.lstat()
    except FileNotFoundError:
        return "missing"
    file_attributes = getattr(entry_stat, "st_file_attributes", 0)
    if is_link_like_stat(entry_stat.st_mode, file_attributes):
        return "link"
    if stat.S_ISREG(entry_stat.st_mode):
        return "file"
    if stat.S_ISDIR(entry_stat.st_mode):
        return "directory"
    return "special"


def _walk_without_links(root: Path) -> list[tuple[Path, str]]:
    entries: list[tuple[Path, str]] = []
    pending = [root]
    while pending:
        directory = pending.pop()
        with os.scandir(directory) as scanned:
            children = sorted(scanned, key=lambda entry: entry.name)
        child_directories: list[Path] = []
        for child in children:
            path = Path(child.path)
            kind = _entry_kind(path)
            entries.append((path, kind))
            if kind == "directory":
                child_directories.append(path)
        pending.extend(reversed(child_directories))
    return entries


def unexpected_canonical_entries(
    target_root: Path,
    allowed_paths: set[Path] | frozenset[Path],
) -> list[tuple[str, Path]]:
    """Return unknown files and every unknown symlink below ``target_root``."""
    root_kind = _entry_kind(target_root)
    if root_kind == "missing":
        return []
    if root_kind != "directory":
        return [(root_kind, target_root)]

    unexpected: list[tuple[str, Path]] = []
    for path, kind in _walk_without_links(target_root):
        if kind == "link":
            if path not in allowed_paths:
                unexpected.append(("symlink/reparse point", path))
            continue
        if path in allowed_paths or kind == "directory":
            continue
        relative = path.relative_to(target_root)
        is_bytecode_cache = (
            kind == "file"
            and path.suffix == ".pyc"
            and "__pycache__" in relative.parts[:-1]
        )
        if not is_bytecode_cache:
            unexpected.append((kind, path))
    return unexpected


def _display_path(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def snapshot_differences(
    expected: dict[Path, str] | None = None,
    *,
    target_root: Path = TARGET_ROOT,
    manual_target_files: set[Path] | frozenset[Path] | None = None,
) -> list[str]:
    """Describe every deviation from the exact canonical source allowlist."""
    if expected is None:
        expected = expected_snapshot()
    if manual_target_files is None:
        manual_target_files = MANUAL_TARGET_FILES
    differences: list[str] = []
    for path, content in sorted(expected.items()):
        relative = _display_path(path)
        kind = _entry_kind(path)
        if kind == "link":
            differences.append(f"symlink/reparse point: {relative}")
        elif kind != "file":
            differences.append(f"missing: {relative}")
        elif path.read_text(encoding="utf-8", errors="strict") != content:
            differences.append(f"outdated: {relative}")

    for path in sorted(manual_target_files):
        relative = _display_path(path)
        kind = _entry_kind(path)
        if kind == "link":
            differences.append(f"symlink/reparse point: {relative}")
        elif kind != "file":
            differences.append(f"missing: {relative}")

    allowed_paths = set(expected) | set(manual_target_files)
    for kind, path in unexpected_canonical_entries(target_root, allowed_paths):
        differences.append(f"unexpected {kind}: {_display_path(path)}")
    return differences


def sync_snapshot(
    expected: dict[Path, str] | None = None,
    *,
    target_root: Path = TARGET_ROOT,
    manual_target_files: set[Path] | frozenset[Path] | None = None,
) -> None:
    """Write known snapshot files without deleting or following unknown entries."""
    if expected is None:
        expected = expected_snapshot()
    if manual_target_files is None:
        manual_target_files = MANUAL_TARGET_FILES

    allowed_paths = set(expected) | set(manual_target_files)
    unsafe = unexpected_canonical_entries(target_root, allowed_paths)
    for path in allowed_paths:
        kind = _entry_kind(path)
        if kind in {"link", "special"}:
            unsafe.append((kind, path))
    if unsafe:
        details = ", ".join(
            f"{kind}: {_display_path(path)}" for kind, path in sorted(unsafe)
        )
        raise RuntimeError(
            f"Refusing to overwrite or delete unknown entries: {details}"
        )

    for path, content in sorted(expected.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        if (
            path.is_file()
            and path.read_text(encoding="utf-8", errors="strict") == content
        ):
            continue
        path.write_text(content, encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write files; fail when the canonical snapshot is outdated.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = expected_snapshot()
    if args.check:
        differences = snapshot_differences(expected)
        if differences:
            print("Canonical package snapshot is outdated:", file=sys.stderr)
            for difference in differences:
                print(f"- {difference}", file=sys.stderr)
            return 1
        print("Canonical package snapshot: OK")
        return 0

    sync_snapshot(expected)
    differences = snapshot_differences(expected)
    if differences:  # pragma: no cover - filesystem failure guard
        raise RuntimeError("Could not synchronize the canonical package")
    print(f"Synced {len(expected)} files into src/fbchat_v2")
    return 0


if __name__ == "__main__":
    sys.exit(main())
